name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile poster
        uses: xu-cheng/latex-action@v2
        with:
          root_file: portrait_poster.tex
          latexmk_use_lualatex: true
      - name: Compile slide
        uses: xu-cheng/latex-action@v2
        with:
          root_file: lidetex
          latexmk_use_lualatex: true
      - name: Upload poster PDF file
        uses: actions/upload-artifact@v3
        with:
          name: portrait_poster
          path: portrait_poster.pdf
      - name: Upload slide PDF file
        uses: actions/upload-artifact@v3
        with:
          name: slide
          path: slide.pdf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            portrait_poster.pdf
            slide.pdf
